var searchData=
[
  ['s_20clasess_0',['Tools around Qt&apos;s clasess',['../group__jkqtptools__qt.html',1,'']]],
  ['scatter_20graphs_1',['scatter graphs',['../group__jkqtplotter__linesymbolgraphs__param.html',1,'Bubble Charts / Parametrized Scatter Graphs'],['../group__jkqtplotter__linesymbolgraphs__scatter.html',1,'Scatter Graphs']]],
  ['scientific_20plotter_20class_2',['JKQTPlotter: Qt based Scientific Plotter Class',['../group__jkqtplotter.html',1,'']]],
  ['sorting_3',['General Algorithms (Sorting ...)',['../group__jkqtptools__algorithms.html',1,'']]],
  ['special_20math_20and_20statistics_20utilities_4',['JKQTMath: Special Math and Statistics Utilities',['../group__jkqtmath.html',1,'']]],
  ['special_20qicon_20generation_5',['Special QIcon generation',['../group__jkqtptools__icons.html',1,'']]],
  ['speed_20optimized_20plotter_20class_6',['JKQTFastPlotter: Speed-Optimized Plotter class',['../group__jkqtfastplotter.html',1,'']]],
  ['statistical_20computations_7',['Statistical Computations',['../group__jkqtptools__math__statistics.html',1,'']]],
  ['statistical_20graphs_20e_20g_20boxplots_8',['Statistical Graphs (e.g. Boxplots ...)',['../group__jkqtplotter__statgraphs.html',1,'']]],
  ['statistics_9',['statistics',['../group__jkqtptools__math__statistics__basic.html',1,'Basic statistics'],['../group__jkqtptools__math__statistics__grouped.html',1,'Grouped statistics']]],
  ['statistics_20to_20plot_20adaptors_10',['Statistics To Plot Adaptors',['../group__jkqtptools__math__statistics__adaptors.html',1,'']]],
  ['statistics_20utilities_11',['JKQTMath: Special Math and Statistics Utilities',['../group__jkqtmath.html',1,'']]],
  ['storage_12',['Data Management and -storage',['../group__jkqtpdatastorage.html',1,'']]],
  ['storage_20classes_13',['Data Storage Classes',['../group__jkqtpdatastorage__classes.html',1,'']]],
  ['string_20conversion_20functions_14',['String(-Conversion) Functions',['../group__jkqtptools__string.html',1,'']]],
  ['structuring_20tools_15',['Code Structuring Tools',['../group__jkqtptools__codestructuring.html',1,'']]],
  ['styling_16',['Mix-In Classes for Plot Styling',['../group__jkqtplotter__basegraphs__stylemixins.html',1,'']]],
  ['styling_20system_17',['Styling System',['../group__jkqtpplotter__styling.html',1,'']]],
  ['styling_20system_20classes_18',['Styling System Classes',['../group__jkqtpplotter__styling__classes.html',1,'']]],
  ['subset_19',['Supported LaTeX-Subset',['../group__jkqtmathtext__supportedlatex.html',1,'']]],
  ['support_20classes_20and_20functions_20',['Support Classes and Functions',['../group__jkqtpplottersupprt.html',1,'']]],
  ['supported_20latex_20subset_21',['Supported LaTeX-Subset',['../group__jkqtmathtext__supportedlatex.html',1,'']]],
  ['supported_20latex_20symbols_22',['Supported LaTeX-Symbols',['../group__jkqtmathtext__supportedlatexsymbols.html',1,'']]],
  ['supported_20markup_20languages_23',['Supported Markup Languages',['../group__jkqtmathtext__general__languages.html',1,'']]],
  ['symbol_20graphs_24',['Line/Symbol Graphs',['../group__jkqtplotter__linesymbolgraphs.html',1,'']]],
  ['symbols_25',['Supported LaTeX-Symbols',['../group__jkqtmathtext__supportedlatexsymbols.html',1,'']]],
  ['system_26',['Styling System',['../group__jkqtpplotter__styling.html',1,'']]],
  ['system_20classes_27',['Styling System Classes',['../group__jkqtpplotter__styling__classes.html',1,'']]]
];
