var searchData=
[
  ['facilities_20for_20jkqtcommon_0',['Library Facilities for JKQTCommon',['../group__jkqtptools__libfacilities.html',1,'']]],
  ['facilities_20for_20jkqtmath_1',['Library Facilities for JKQTMath',['../group__jkqtmath__libfacilities.html',1,'']]],
  ['facilities_20for_20jkqtmathtext_2',['Library Facilities for JKQTMathText',['../group__jkqtmathtext__libfacilities.html',1,'']]],
  ['filled_20polygon_20area_20graphs_3',['Filled Polygon/Area Graphs',['../group__jkqtplotter__filledgraphs.html',1,'']]],
  ['fits_20regression_4',['Polynomial Fits/Regression',['../group__jkqtptools__math__statistics__poly.html',1,'']]],
  ['font_20handling_5',['Font Handling',['../group__jkqtmathtext__fonthandling.html',1,'']]],
  ['for_201_20dimensional_20histograms_6',['Kernels for 1-dimensional Histograms',['../group__jkqtptools__math__statistics__1dkde__kernels.html',1,'']]],
  ['for_202_20dimensional_20histograms_7',['Kernels for 2-dimensional Histograms',['../group__jkqtptools__math__statistics__2dkde__kernels.html',1,'']]],
  ['for_20concurrency_8',['Tools, Templates and Classes for Concurrency',['../group__jkqtptools__concurrency.html',1,'']]],
  ['for_20error_20indicators_9',['Mix-In Classes for Error Indicators',['../group__jkqtplotter__basegraphserrors.html',1,'']]],
  ['for_20graphs_10',['for graphs',['../group__jkqtplotter__basegraphs.html',1,'Baseclasses for Graphs'],['../group__jkqtplotter__mixins.html',1,'Mix-in classes for Graphs']]],
  ['for_20image_20drawing_11',['Tool Functions &amp; Classes for Image Drawing',['../group__jkqtplotter__imagelots__tools.html',1,'']]],
  ['for_20jkqtcommon_12',['Library Facilities for JKQTCommon',['../group__jkqtptools__libfacilities.html',1,'']]],
  ['for_20jkqtfastplotter_13',['Tool DEPRECATED: Functions, Enums, Classes for JKQTFastPlotter',['../group__jkqtfastplotter__tools.html',1,'']]],
  ['for_20jkqtmath_14',['Library Facilities for JKQTMath',['../group__jkqtmath__libfacilities.html',1,'']]],
  ['for_20jkqtmathtext_15',['for jkqtmathtext',['../group__jkqtmathtext__libfacilities.html',1,'Library Facilities for JKQTMathText'],['../group__jkqtmathtext__items.html',1,'Render-Tree Items for JKQTMathText'],['../group__jkqtmathtext__tools.html',1,'Tool Functions and Types for JKQTMathText']]],
  ['for_20mathematical_20expressions_16',['Parser/Evaluator for Mathematical Expressions',['../group__jkqtptools__math__parser.html',1,'']]],
  ['for_20palettes_17',['Tool Functions to Build Lookup-Tables for Palettes',['../group__jkqtplotter__imagelots__tools___l_u_t_s.html',1,'']]],
  ['for_20plot_20styling_18',['Mix-In Classes for Plot Styling',['../group__jkqtplotter__basegraphs__stylemixins.html',1,'']]],
  ['for_20properties_20of_20jkqtbaseplotter_20jkqtplotter_19',['Comboboxes for Properties of JKQTBasePlotter/JKQTPlotter',['../group__jkqtpcomboboxes.html',1,'']]],
  ['for_20qt_20',['JKQTMathText LaTeX-Renderer for Qt',['../group__jkqtmathtext.html',1,'']]],
  ['form_20designer_21',['How to use JKQTPlotter in the Qt Form Designer',['../group__jkqtplotter__general__usage__qtcreator.html',1,'']]],
  ['function_20documentation_22',['Type/Class/Function Documentation',['../group__jkqtplotter__classdoc.html',1,'']]],
  ['function_20graphs_23',['Function Graphs',['../group__jkqtplotter__functiongraphs.html',1,'']]],
  ['functions_24',['functions',['../group__jkqtmathtext__interaltools.html',1,'Library-internal Types and Functions'],['../group__jkqtptools__string.html',1,'String(-Conversion) Functions'],['../group__jkqtpplottersupprt.html',1,'Support Classes and Functions']]],
  ['functions_20and_20types_20for_20jkqtmathtext_25',['Tool Functions and Types for JKQTMathText',['../group__jkqtmathtext__tools.html',1,'']]],
  ['functions_20classes_20for_20image_20drawing_26',['Tool Functions &amp; Classes for Image Drawing',['../group__jkqtplotter__imagelots__tools.html',1,'']]],
  ['functions_20enums_20classes_20for_20jkqtfastplotter_27',['Tool DEPRECATED: Functions, Enums, Classes for JKQTFastPlotter',['../group__jkqtfastplotter__tools.html',1,'']]],
  ['functions_20to_20build_20lookup_20tables_20for_20palettes_28',['Tool Functions to Build Lookup-Tables for Palettes',['../group__jkqtplotter__imagelots__tools___l_u_t_s.html',1,'']]],
  ['functions_20tools_29',['functions tools',['../group__jkqtptools__general.html',1,'General Functions &amp; Tools'],['../group__jkqtptools__math__basic.html',1,'Mathematical Functions &amp; Tools']]]
];
