var searchData=
[
  ['s_20new_20release_20notes_20versions_0',['What&apos;s New (Release Notes/Versions)',['../page_whatsnew.html',1,'']]],
  ['scatter_20graph_1',['scatter graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph'],['../_j_k_q_t_plotterscatter.html',1,'Example (JKQTPlotter): Very simple scatter-graph']]],
  ['scatter_20graph_20with_20custom_20symbols_2',['scatter graph with custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols'],['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'Example (JKQTPlotter): Scatter-graph with custom symbols']]],
  ['scatter_20graph_20with_20parametrized_20symbols_20colors_3',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['screenshots_4',['JKQTPlotter: Screenshots',['../md_screenshots_2_r_e_a_d_m_e.html',1,'']]],
  ['secondary_20axes_5',['Example (JKQTPlotter): Secondary Axes',['../_j_k_q_t_plotter_secondary_axes.html',1,'exampleTutorialProjects']]],
  ['security_20policy_6',['Security Policy',['../md__s_e_c_u_r_i_t_y.html',1,'']]],
  ['set_20explorer_7',['Example (JKQTPlotter): Mandelbrot Set Explorer',['../_j_k_q_t_plotter_mandelbrot.html',1,'exampleTutorialProjects']]],
  ['several_20plots_8',['Example (JKQTPlotter): Laying out Several Plots',['../_j_k_q_t_plotter_multi_plot_layout.html',1,'exampleTutorialProjects']]],
  ['showin_20a_201_20channel_20cimg_20image_9',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['showin_20a_201_20channel_20opencv_20cv_3a_3amat_10',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['showing_20a_203_20channel_20cimg_20image_11',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['showing_20a_203_20channel_20opencv_20cv_3a_3amat_12',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['simple_20barchart_13',['Example (JKQTPlotter): Simple barchart',['../_j_k_q_t_plotter_barcharts.html',1,'exampleTutorialProjects']]],
  ['simple_20graph_20labels_20example_14',['Example (JKQTPlotter): Simple Graph Labels Example',['../_j_k_q_t_plotter_graph_labels_example.html',1,'']]],
  ['simple_20impulse_20plots_15',['Example (JKQTPlotter): Simple impulse plots',['../_j_k_q_t_plotter_impulse_plots.html',1,'exampleTutorialProjects']]],
  ['simple_20line_20graph_16',['Example (JKQTPlotter): Very simple line-graph',['../_j_k_q_t_plotter_simple_test.html',1,'exampleTutorialProjects']]],
  ['simple_20line_20graph_20with_20error_20bars_17',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['simple_20line_20graph_20with_20live_20data_20speed_20test_18',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_19',['Example (JKQTPlotter): Simple math image plot',['../_j_k_q_t_plotter_image_plot.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20showin_20a_201_20channel_20cimg_20image_20',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20showin_20a_201_20channel_20opencv_20cv_3a_3amat_21',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20showing_20a_203_20channel_20cimg_20image_22',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20with_20modifier_20datat_23',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20without_20use_20of_20central_20jkqtdatastore_24',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20rgb_20cmy_20image_20plot_25',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['simple_20rgb_20image_20plot_20showing_20a_203_20channel_20opencv_20cv_3a_3amat_26',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['simple_20scatter_20graph_27',['Example (JKQTPlotter): Very simple scatter-graph',['../_j_k_q_t_plotterscatter.html',1,'exampleTutorialProjects']]],
  ['simple_20stacked_20barchart_28',['Example (JKQTPlotter): Simple stacked barchart',['../_j_k_q_t_plotter_stacked_bar_chart.html',1,'exampleTutorialProjects']]],
  ['simple_20usage_20example_29',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['speed_20test_30',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['stacked_20barchart_31',['Example (JKQTPlotter): Simple stacked barchart',['../_j_k_q_t_plotter_stacked_bar_chart.html',1,'exampleTutorialProjects']]],
  ['statistical_20distribution_20of_20data_32',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['statistics_20library_33',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['statistics_20with_20jkqtpdatastore_34',['statistics with jkqtpdatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html',1,'Tutorial (JKQTPDatastore): 1-Dimensional Group Statistics with JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore']]],
  ['step_20line_20plots_20in_20different_20styles_35',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['styles_36',['styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles'],['../_j_k_q_t_plotter_special_step_line_plot.html',1,'Example (JKQTPlotter): Step Line Plots in Different Styles']]],
  ['styling_37',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['styling_20a_20jkqtplotter_38',['Tutorial (JKQTPlotter): Styling a JKQtPlotter',['../_j_k_q_t_plotter_styling.html',1,'exampleTutorialProjects']]],
  ['styling_20different_20aspects_20of_20boxplots_39',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['symbols_40',['symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols'],['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'Example (JKQTPlotter): Scatter-graph with custom symbols']]],
  ['symbols_20and_20line_20styles_41',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['symbols_20colors_42',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]]
];
