var searchData=
[
  ['central_20jkqtdatastore_0',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['channel_20cimg_20image_1',['channel cimg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image'],['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image']]],
  ['channel_20opencv_20cv_3a_3amat_2',['channel opencv cv::mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat'],['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat']]],
  ['cimg_20image_3',['cimg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image'],['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image']]],
  ['cmake_4',['Build using CMake',['../page_buildinstructions__c_m_a_k_e.html',1,'page_buildinstructions']]],
  ['cmake_20example_5',['Example (JKQTPlotter): CMake Example',['../_j_k_q_t_c_make_link_example.html',1,'exampleTutorialProjects']]],
  ['cmy_20image_20plot_6',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['code_20of_20conduct_7',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['color_20fill_20mode_8',['Example (JKQTPlotter): Barchart With Two-Color Fill-Mode',['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'exampleTutorialProjects']]],
  ['colors_9',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['command_20line_20utility_20jkqtmathtext_5frender_10',['Tool (JKQTMathText): Command-Line Utility jkqtmathtext_render',['../_j_k_q_t_math_text_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['command_20line_20utility_20jkqtplotter_5fdoc_5fimagegenerator_11',['Tool (JKQTMathText): Command-Line Utility jkqtplotter_doc_imagegenerator',['../_j_k_q_t_plotter_doc_image_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['conduct_12',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['contour_20plots_13',['Example (JKQTPlotter): Contour Plots',['../_j_k_q_t_plotter_contour_plot.html',1,'exampleTutorialProjects']]],
  ['contributing_14',['Contributing',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_15',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['covenant_20code_20of_20conduct_16',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['curve_20plots_17',['Example (JKQTPlotter): Filled Curve Plots',['../_j_k_q_t_plotter_filled_graphs.html',1,'exampleTutorialProjects']]],
  ['curves_18',['Example (JKQTPlotter): Plotting Parametric Curves',['../_j_k_q_t_plotter_parametric_curves.html',1,'exampleTutorialProjects']]],
  ['curves_20as_20line_20graphs_19',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['custom_20draw_20functor_20',['Example (JKQTPlotter): Barchart With Custom Draw Functor',['../_j_k_q_t_plotter_barcharts_custom_draw_functor.html',1,'exampleTutorialProjects']]],
  ['custom_20palettes_21',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['custom_20symbols_22',['custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols'],['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'Example (JKQTPlotter): Scatter-graph with custom symbols']]],
  ['cv_3a_3amat_23',['cv::mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat'],['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat']]]
];
