var searchData=
[
  ['terms_20for_20jkqtplotter_0',['Licensing Terms for JKQTPlotter',['../licensepage.html',1,'']]],
  ['test_1',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['test_20application_2',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['the_20statistics_20library_3',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['threaded_20parallel_20plotting_4',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]],
  ['through_20origin_5',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['time_20axes_6',['Example (JKQTPlotter): Date/Time Axes',['../_j_k_q_t_plotter_date_time_axes.html',1,'exampleTutorialProjects']]],
  ['todo_20list_20für_20future_20releases_20versions_7',['Todo List für Future Releases/Versions',['../page_todo.html',1,'']]],
  ['tool_20jkqtmathtext_20_3a_20command_20line_20utility_20jkqtmathtext_5frender_8',['Tool (JKQTMathText): Command-Line Utility jkqtmathtext_render',['../_j_k_q_t_math_text_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['tool_20jkqtmathtext_20_3a_20command_20line_20utility_20jkqtplotter_5fdoc_5fimagegenerator_9',['Tool (JKQTMathText): Command-Line Utility jkqtplotter_doc_imagegenerator',['../_j_k_q_t_plotter_doc_image_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_201_20dimensional_20group_20statistics_20with_20jkqtpdatastore_10',['Tutorial (JKQTPDatastore): 1-Dimensional Group Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20advanced_201_20dimensional_20statistics_20with_20jkqtpdatastore_11',['Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20advanced_202_20dimensional_20statistics_20with_20jkqtpdatastore_12',['Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20basic_20usage_20of_20jkqtpdatastore_13',['Tutorial (JKQTPDatastore): Basic Usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20iterator_20based_20usage_20of_20jkqtpdatastore_14',['Tutorial (JKQTPDatastore): Iterator-Based usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20regression_20analysis_20with_20the_20statistics_20library_15',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtplotter_20_3a_20styling_20a_20jkqtplotter_16',['Tutorial (JKQTPlotter): Styling a JKQtPlotter',['../_j_k_q_t_plotter_styling.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtplotter_20_3a_20user_20interactions_20in_20jkqtplotter_17',['Tutorial (JKQTPlotter): User-Interactions in JKQtPlotter',['../_j_k_q_t_plotter_user_interaction.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtplotter_20_3a_20using_20a_20jkqtplotter_20inside_20a_20qt_20user_20interface_20designer_20ui_20file_18',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['tutorial_20projects_19',['Example &amp; Tutorial Projects',['../example_tutorial_projects.html',1,'']]],
  ['two_20color_20fill_20mode_20',['Example (JKQTPlotter): Barchart With Two-Color Fill-Mode',['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'exampleTutorialProjects']]],
  ['types_20of_20errorindicators_21',['Example (JKQTPlotter): Different Types of Errorindicators',['../_j_k_q_t_plotter_error_bar_styles.html',1,'exampleTutorialProjects']]]
];
