var searchData=
[
  ['palettes_0',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['parallel_20plotting_1',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]],
  ['parametric_20curves_2',['Example (JKQTPlotter): Plotting Parametric Curves',['../_j_k_q_t_plotter_parametric_curves.html',1,'exampleTutorialProjects']]],
  ['parametric_20mathematical_20curves_20as_20line_20graphs_3',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['parametrized_20scatter_20graph_4',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['parametrized_20scatter_20graph_20with_20custom_20symbols_5',['Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'exampleTutorialProjects']]],
  ['parametrized_20symbols_20colors_6',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['parsed_20mathematical_20functions_20as_20line_20graphs_7',['Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_parsed_function_plot.html',1,'exampleTutorialProjects']]],
  ['plot_8',['plot',['../_j_k_q_t_plotter_image_plot.html',1,'Example (JKQTPlotter): Simple math image plot'],['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'Example (JKQTPlotter): Simple Math RGB/CMY Image Plot']]],
  ['plot_20example_9',['Example (JKQTPlotter): Vector Field Plot Example',['../_j_k_q_t_plotter_vector_field_example.html',1,'exampleTutorialProjects']]],
  ['plot_20showin_20a_201_20channel_20cimg_20image_10',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['plot_20showin_20a_201_20channel_20opencv_20cv_3a_3amat_11',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['plot_20showing_20a_203_20channel_20cimg_20image_12',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['plot_20showing_20a_203_20channel_20opencv_20cv_3a_3amat_13',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['plot_20with_20axes_20through_20origin_14',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['plot_20with_20modifier_20datat_15',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['plot_20without_20use_20of_20central_20jkqtdatastore_16',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['plots_17',['plots',['../_j_k_q_t_plotter_contour_plot.html',1,'Example (JKQTPlotter): Contour Plots'],['../_j_k_q_t_plotter_filled_graphs.html',1,'Example (JKQTPlotter): Filled Curve Plots'],['../_j_k_q_t_plotter_multi_plot_layout.html',1,'Example (JKQTPlotter): Laying out Several Plots'],['../_j_k_q_t_plotter_impulse_plots.html',1,'Example (JKQTPlotter): Simple impulse plots'],['../_j_k_q_t_plotter_violinplot_graphs.html',1,'Example (JKQTPlotter): Violin Plots'],['../_j_k_q_t_plotter_wiggle_plots.html',1,'Example (JKQTPlotter): Wiggle Plots']]],
  ['plots_20in_20different_20styles_18',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['plots_20of_20geometric_20objects_20for_20documentation_19',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['plots_20with_20custom_20palettes_20',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['plotting_21',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]],
  ['plotting_20a_20statistical_20distribution_20of_20data_22',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['plotting_20arrows_23',['Example (JKQTPlotter): Plotting Arrows',['../_j_k_q_t_plotter_geometric_arrows.html',1,'exampleTutorialProjects']]],
  ['plotting_20geometric_20objects_24',['Example (JKQTPlotter): Plotting Geometric Objects',['../_j_k_q_t_plotter_geometric_graphs.html',1,'exampleTutorialProjects']]],
  ['plotting_20library_25',['JKQTPlotter - A Qt Plotting Library',['../index.html',1,'']]],
  ['plotting_20mathematical_20functions_20as_20line_20graphs_26',['Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'exampleTutorialProjects']]],
  ['plotting_20parametric_20curves_27',['Example (JKQTPlotter): Plotting Parametric Curves',['../_j_k_q_t_plotter_parametric_curves.html',1,'exampleTutorialProjects']]],
  ['plotting_20parametric_20mathematical_20curves_20as_20line_20graphs_28',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['plotting_20parsed_20mathematical_20functions_20as_20line_20graphs_29',['Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_parsed_function_plot.html',1,'exampleTutorialProjects']]],
  ['policy_30',['Security Policy',['../md__s_e_c_u_r_i_t_y.html',1,'']]],
  ['projects_31',['Example &amp; Tutorial Projects',['../example_tutorial_projects.html',1,'']]]
];
