var searchData=
[
  ['a_201_20channel_20cimg_20image_0',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['a_201_20channel_20opencv_20cv_3a_3amat_1',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['a_203_20channel_20cimg_20image_2',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['a_203_20channel_20opencv_20cv_3a_3amat_3',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['a_20graph_4',['Example (JKQTPlotter): QImage as a Graph',['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'exampleTutorialProjects']]],
  ['a_20jkqtplotter_5',['Tutorial (JKQTPlotter): Styling a JKQtPlotter',['../_j_k_q_t_plotter_styling.html',1,'exampleTutorialProjects']]],
  ['a_20jkqtplotter_20inside_20a_20qt_20user_20interface_20designer_20ui_20file_6',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['a_20parametrized_20scatter_20graph_7',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['a_20qt_20plotting_20library_8',['JKQTPlotter - A Qt Plotting Library',['../index.html',1,'']]],
  ['a_20simple_20usage_20example_9',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['a_20statistical_20distribution_20of_20data_10',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['a_20test_20application_11',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['advanced_201_20dimensional_20statistics_20with_20jkqtpdatastore_12',['Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'exampleTutorialProjects']]],
  ['advanced_202_20dimensional_20statistics_20with_20jkqtpdatastore_13',['Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'exampleTutorialProjects']]],
  ['advanced_20line_20and_20fill_20styling_14',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['an_20artistic_20image_20with_20a_20parametrized_20scatter_20graph_15',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['analysis_20with_20the_20statistics_20library_16',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['and_20fill_20styling_17',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['and_20line_20styles_18',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['application_19',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['arrows_20',['Example (JKQTPlotter): Plotting Arrows',['../_j_k_q_t_plotter_geometric_arrows.html',1,'exampleTutorialProjects']]],
  ['artistic_20image_20with_20a_20parametrized_20scatter_20graph_21',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['as_20a_20graph_22',['Example (JKQTPlotter): QImage as a Graph',['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'exampleTutorialProjects']]],
  ['as_20line_20graphs_23',['as line graphs',['../_j_k_q_t_plotter_function_plots.html',1,'Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs'],['../_j_k_q_t_plotter_eval_curves.html',1,'Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs'],['../_j_k_q_t_plotter_parsed_function_plot.html',1,'Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs']]],
  ['aspects_20of_20boxplots_24',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['axes_25',['axes',['../_j_k_q_t_plotter_date_time_axes.html',1,'Example (JKQTPlotter): Date/Time Axes'],['../_j_k_q_t_plotter_secondary_axes.html',1,'Example (JKQTPlotter): Secondary Axes']]],
  ['axes_20through_20origin_26',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['axis_27',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]]
];
